### PR TITLE
Display risk levels of best practices in exported XLSX file

### PR DESCRIPTION
**Pull request by binchoo**
This issue is related to `Well-Architected Tool> Helpful Resources> Export to XLSX` tool.

*Description of changes:*
- Modified the xlsx file to show the sustainability pillar
- Modified the xlsx to contain a new column for best-practice risk levels

The tool helps to export a XLSX file from a well-architected workload that my AWS account answered to.

I believe the exported file is useful because it gathers, in a sheet, all questions and choices about the well-architected pillars(except sustainability). 
A customer can skim through the sheet to get to know about well-architected framework, instead of clicking all contents from the WAT console or the AWS docs.

I'm now concerning that:
  - the xlsx file should include the sustainability pillar obviously.
  - a column that shows `Level of risk exposed if this best practice is not established` may be added.

A customer can feel exhuasted when answering to every choice under a question. At this moment, the risk level is an important metric for prioritizing the choices, and helps the customer to focus on more important best practices.

We can find the level of risk from each best-practice document, however it seems WAT console or cli/sdk are not providing the information about it.

I'm suggesting a new column for best-practice risks, which are crawled data from the documents.
image
스크린샷 2023-06-21 오후 3 36 10

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

c.c @ericpullen

### CODE REVIEW

**Comment by awsdunc** [comment]
Hey @binchoo is this tested and ready to merge?

**Comment by binchoo** [comment]
Hi @awsdunc 
Yes, please proceed. I tested on serveral existing workloads and a temporary workload.

**Comment by binchoo** [comment]
Sorry @awsdunc I found an issue case and fixed it.

*Description of changes*:
- Fixed ImprovementPlanUrl being null due to unanswered questions
image

**Comment by binchoo** [comment]
@awsdunc Hello. I'd like to hear any comment from you. Is an update needed?

**Pull request closed without merging**
