### PR TITLE
Added Savings plan owner account to the "Account Spend of Shared Savings Plan" query to make it more readable and useful for analysis

### PR DESCRIPTION
**Pull request by davidecoccia**
*Issue #, if available:*

*Description of changes:* I've added the effective Savings Plan owner by parsing the SP ARN. This allows easy reporting on account SP self-consumption vs sharing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awsdunc** [comment]
Please can you confirm if this is ready for review/merge?

**Comment by davidecoccia** [comment]
from my side confirmed, ready to be reviewed and merged

**Comment by awsdunc** [comment]
@amazonchris can you have a quick look at this PR please?

**Review by amazonchris — APPROVED** [review]
Reviewed and tested query, makes sense to have the purchasing account ID displayed as one of the columns.

**Comment by amazonchris** [comment]
> @amazonchris can you have a quick look at this PR please?

Done, added review

**Pull request merged**
