### PR TITLE
fix data transfer view for cases with single month digit in CUR

### PR DESCRIPTION
**Pull request by u-mancini**
*Issue #, if available:* https://github.com/awslabs/aws-well-architected-labs/issues/931

*Description of changes:* Modified the date filter condition to make it compatible with all cur report implementation (some of them have single digit "month" partition)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awsdunc** [comment]
Please can you confirm if this is ready for review/merge?

**Comment by u-mancini** [comment]
> Please can you confirm if this is ready for review/merge?

Yes, I confirm

**Comment by buulq** [comment]
Hi @u-mancini,

How can I fix this issue?

**Review by iakov-aws — APPROVED** [review]

**Comment by buulq** [comment]
How I can update my current dashboard to run new code?

**Comment by u-mancini** [comment]
> How I can update my current dashboard to run new code?

You can run the Athena query again following the instruction here : https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/code/7_view7/#create-view

**Comment by buulq** [comment]
Hi @u-mancini,

It's worked, thanks a lot for your support.

**Pull request merged**
