### PR TITLE
300 Resiliency Lab Updates

### PR DESCRIPTION
**Pull request by hakenmt**
*Issue #, if available:*

*Description of changes:*
Updated to netcoreapp3.1 for cross platform builds. Fixed all async methods and waits. More detailed command line output. Include simple powershell build file to create windows, linux, and mac specific builds. Can be run on these platforms without installing dotnet.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
Thank you Michael!

Can you help me to debug the following issues?

1. Command failed with error "Unkown exception occured AWS was not able to validate the provided access credentials"

I ran the `aws` CLI right after to show that credentials were indeed set

```
C:\Temp\win10-x64>.\AppResiliency EC2  vpc-0f4e84d8544d2dbf4
Unkown exception occured AWS was not able to validate the provided access credentials

C:\Temp\win10-x64>aws s3 ls
2020-09-14 13:18:46 cf-templates-15et33j35k217-us-east-1
2020-05-26 13:57:41 cf-templates-15et33j35k217-us-east-2
2020-05-26 10:56:31 cloudtrail-awslogs-847367160914-5rztxtac-isengard-do-not-delete
2021-09-21 22:38:31 do-not-delete-gatedgarden-audit-847367160914
```

2. Is there any way we can get the entire executable in the EXE file?

I see that it requires the DLLs in the same folder or it won't run.  But in the previous version we only needed the EXE… is there a way to package it all up in the EXE file?


3. The ARM64 version does not build

```
  Determining projects to restore...
  Restored C:\Temp\AppResiliency\AppResiliency\AppResiliency.csproj (in 3.27 sec).
C:\Program Files\dotnet\sdk\3.1.413\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(166,5): error NETSDK1032: The RuntimeIdentifier platform 'linux-arm64' and the PlatformTarget 'x64' must be compatible. [C:\Temp\AppResiliency\AppResiliency\AppResiliency.csproj]
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
```

4. "Unkown" and "occurred" are misspelled :-)

**Comment by setheliot** [comment]
5. I tried running from a completely different Windows machine

```
>.\AppResiliency.exe EC2 vpc-0f4e84d8544d2dbf4
Unkown exception occured An attempt was made to access a socket in a way forbidden by its access permissions.
```

**Comment by hakenmt** [comment]
> Is there any way we can get the entire executable in the EXE file?
> 
> I see that it requires the DLLs in the same folder or it won't run. But in the previous version we only needed the EXE… is there a way to package it all up in the EXE file?
> 
> Also the ZIP file is 93 MB! seems large

Yes, I can update the package to build as a single file. The resulting executable will auto extract itself when run. The reason that the package is so large is that these are being built as a self-contained app for each platform. It packages all of the necessary dependencies with the application so that they can be run natively without .net being installed.

I ran all of my tests from my Cloudshell environment and didn't get any exceptions. Let me try on a few other platforms to see if I can reproduce.

**Comment by setheliot** [comment]
Thank you Michael!  
* I have merged all your changes into the `seliot` branch for now and will merge to master later. 
* Your Windows EXE has been uploaded to our S3 bucket
* You have been given a contributor credit on the lab main page

**Pull request closed without merging**
