### PR TITLE
Cur Query Library - New Query - Top 50 Resource Movers

### PR DESCRIPTION
**Pull request by amazonchris**
*Description of changes:
This query produces the top 50 moving resources by 1/ cost delta and 2/ change in percentage. The parameters have been adjusted for comparison of resources from three days prior and two days prior as CUR may take up to 48 hours to update all estimated charges. Additionally, this query pulls only resources with greater than $5 in unblended cost in order to reduce noise from resources which did not exist in one of the look back periods or spun up at the end of one of the look back periods. Adjust these parameters to suite your needs.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aws-jrmarks** [comment]
Taking a look

**Review by aws-jrmarks — DISMISSED** [review]
Tested queries against customer data, and they run as intended without errors. I'm fine with them in their current form.

I want to point out that the data-processing-capacity query uses `product_vcpu` counts, and that at smaller sizes (nano, micro, etc), still shows a 1 value even though they don't get a "whole" core. Also, not all vcpus are created equal, so customers should be aware when using that field (and aggregating on it).

**Review by kyle-damas — APPROVED** [review]
Tested for accuracy and tested site renders.

**Review by aws-jrmarks — APPROVED** [review]
approved

**Review by aws-jrmarks — APPROVED** [review]
whoops, didn't select the files last time, approving again.

**Review by awsdunc — APPROVED** [review]

**Pull request merged**
