### PR TITLE
better description for fronted term 300_Health_Checks_and_Dependencies

### PR DESCRIPTION
**Pull request by lpiedade**
*Description of changes:* typo fix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
Hi @lpiedade 

Thank you for your contribution.

I see you want to change "fronted" to "frontend" in the following statement

> The service is a web server running on Amazon EC2 fronted by an Elastic Load Balancer reverse-proxy, with a dependency on Amazon DynamoDB.

Please note this was not a typo.  "EC2 fronted by an Elastic Load Balancer" was the intended phrasing, indicating the EC2 is preceded by the ELB.   But I do now see this is clunky phrasing, and would present challenges to those who are not native English speakers.

A better phrasing might be

> The service is a web server running on Amazon EC2. It has an Elastic Load Balancer reverse-proxy in front of it, and has a dependency on Amazon DynamoDB.

If you would like to update your PR to this new phrasing, or something similar, then I will gladly pull it.

**Comment by setheliot** [comment]
Hi @lpiedade did you want to make this updated change?  If not, then no problem, I will go ahead and do it

**Comment by lpiedade** [comment]
Hi @setheliot you're right. It was my mistake about the "fronted" meaning. I agree with your suggestion and I already updated. Tks.

**Comment by setheliot** [comment]
Thanks!

**Pull request merged**
