### PR TITLE
Updates to Lab Guide for to REL 300 - some lite md linting and fixing a previous commit

### PR DESCRIPTION
**Pull request by setheliot**
*Issue #, if available:*

*Description*
* light md linting for lab guide - works on both GitHub and https://wellarchitectedlabs.com/
* fix an omission in https://github.com/awslabs/aws-well-architected-labs/pull/30/commits/0216a54c53267fd521bd79c217754ad2a21d6573

Verified both on GitHub and in mkdocs generated html

Imminent changes will be made to actual content, so this was just a preliminary change to get the formatting in order

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
see output here https://github.com/setheliot/aws-well-architected-labs/blob/md_lint_lite2/Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/Lab_Guide.md

**Comment by adhorn** [comment]
@setheliot  Shouldn't we update all the screenshots at the same time? A lot of them are from the old console and also the 2 regions deployment.

**Comment by setheliot** [comment]
@adhorn I did not update any screenshots here.  This was **mostly** updates to MD and formatting, so as to give a solid base for the upcoming content changes

**Comment by setheliot** [comment]
got the OK from @RodneyLester to merge

**Pull request merged**
