### PR TITLE
camiload DR Spanish Workshops

### PR DESCRIPTION
**Pull request by camilo23401**
*Immersion Day Asana, traduction task assigned to camiload*

*Description of changes:*

Added the translated content for the DR Workshops 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
I am concerned that you have lots of files here not related to the translation, and branch conflicts.

It looks like you perhaps did not merge with master before submitting the PR.

This PR should not be merged as it is now.  You need to fix it to 1. only contain the files you changed 2. if you did change the other (un-related to translation) files, then put those in a separate commit and separate PR

**Review by setheliot — CHANGES_REQUESTED** [review]
I am concerned that you have lots of files here not related to the translation, and branch conflicts.

It looks like you perhaps did not merge with master before submitting the PR.

This PR should not be merged as it is now. You need to fix it to 1. only contain the files you changed 2. if you did change the other (un-related to translation) files, then put those in a separate commit and separate PR

**Comment by camilo23401** [comment]
Merges got messy, I will open a new pull request with this fixed.

**Comment by setheliot** [comment]
Thank you @camilo23401 ,however your latest commits do not fix the issue.  Please look under the FIles Changed tab -- it should _only_ show the files _you_ changed.  It should not show Cost lab changes.

If you cannot fix this in git, your best put may be to do the following
* Copy all your changes to a safe place
* Checkout master and pull
* Create a new branch
* copy changes into the branch
* commit and make a **new** PR

**Pull request closed without merging**
