### PR TITLE
Antross fixes

### PR DESCRIPTION
**Pull request by allcentury**
*Issue #, if available:* N/A

* Fix HTML Indentation
* Fix grammatical errors

Can anyone tell me if `Prequisites` is actually supposed to be `Prerequisites`? If so, I'm happy to update those.  [Example](https://www.wellarchitectedlabs.com/reliability/200_labs/200_bidirectional_replication_for_s3/).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
@benjipotter , SEC change looks good, so I pulled it
image

**Comment by setheliot** [comment]
@allcentury thank you for these fixes!

> Can anyone tell me if `Prequisites` is actually supposed to be `Prerequisites`?

Right now the pre reqs are having an AWS account an admin login.  What do you propose

**Comment by allcentury** [comment]
@setheliot sorry, I meant the word itself, today it shows:

Prequisites - another term for perk

vs. 

Prerequisites - something that is required as a prior condition to something else

**Comment by setheliot** [comment]
ah, no, it should be `Prerequisites` like all the other.... I will fix it

**Comment by setheliot** [comment]
Thanks again @allcentury :-)

https://github.com/awslabs/aws-well-architected-labs/commit/df0928d995748bb5835ddb42755ba7a936e9107e

**Pull request merged**
