### PR TITLE
Module 5 - Hot Standby using Route 53 Application Recovery controller (ARC)

### PR DESCRIPTION
**Pull request by andrew-grischenko**
New Module 5 - Hot Standby using Route 53 Application Recovery controller (ARC)
It also added some incremental resources to Module 4 CF file HotStandby.yaml which are dormant in Module 4.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awsdunc** [comment]
Is this ready for review? If so do you need people to review it?

**Comment by andrew-grischenko** [comment]
@awsdunc Yes, please! I spoke to Jennifer Moran, she said she will have a look this week. I can't assign the PR

**Comment by awsdunc** [comment]
@jmoran8888 do you have capacity to review this please?

**Comment by jmoran8888** [comment]
Yes doing today - thanks !

**Comment by andrew-grischenko** [comment]
The latest changes for the issues identified in testing have been committed - please review and merge.

**Comment by andrew-grischenko** [comment]
Merged by [jmoran8888](https://github.com/jmoran8888) using a separate PR

**Pull request closed without merging**
